#!/usr/bin/env python3
import rospy
import json
import csv, os
import logging
from std_msgs.msg import String
import rospkg
import time
import sys
# initialization
if __name__ == '__main__':
    
    print(sys.path)
    
    try:
        pub = rospy.Publisher('/move/cmd_str', String, queue_size=1)
        rospy.init_node('circle')
        rate = rospy.Rate(1) # 10hz
        while not rospy.is_shutdown():
            rospy.loginfo("Turning Left.")
            pub.publish("left")
            rate.sleep()

        pub.publish("stop")
    except Exception as e:
        logging.exception("An error occurred")